// This file contains the hierarchy for Downtime reasons.
// Level 1 (L1) -> Downtime Type
// Level 2 (L2) -> Category
// Level 3 (L3) -> Sub-Category

export const ACTUAL_DOWNTIME_DATA: Record<string, Record<string, string[]>> = {
  
  
  "Machine Breakdown": {
    "No Reason": ["No Reason"],
    "Holding Furnace B/D": [
      "Metal temperature voltage not reach",
      "Metal temperature Low/High",
      "Heater coil not available",
      "Heater coil broken (or)Damage",
      "Coil Cut off",
      "Transformer Burst",
      "Temperature Poke Yoke Not working",
      "Communication Cable Failure"
    ],
    "Main Control Panel": [
      "Power Supply Faulty",
      "Main MCB Tripped/Defective",
      "Loose Connection",
      "MCB Tripped",
      "PLC In Fault Mode",
      "Drive Tripped",
      "Panel Temperature High",
      "Contactor Failure",
      "IO Card Faulty",
      "Relay Faulty",
      "Timer Faulty",
      "Fuse Blown",
      "Multicore Cable Shorting",
      "Field Wiring Short"
    ],
    "Operator Control Panel": [
      "HMI Not Working",
      "No Display",
      "Touch Not Working",
      "Selector Switch/Push Button Faulty",
      "Operator Panel Temperature High",
      "PLC In Fault Mode"
    ],
    "Operator Control Desk": [
      "HMI Not Working",
      "No Display",
      "Touch Not Working",
      "Selector Switch/Push Button Faulty",
      "Operator Panel Temperature High",
      "No Communication",
      "PLC In Fault Mode"
    ],
    "Main Hydraulic Pump": [
      "Motor Tripping/Not Running",
      "Motor Abnormal Noise",
      "Motor Temperature High",
      "Pump Abnormal Noise",
      "Pump Temperature High",
      "Pump Coupling Loose",
      "Pressure Not Build",
      "Suction Stainer Clogged",
      "Pressure Filter Clogged",
      "Hyd Oil Leakage",
      "Hyd Oil Temperature High",
      "Hyd Oil Level Low",
      "Hyd Oil Contaminated",
      "Pressure Relief Valve Not Working",
      "Loading/Unloading Valve Not Proper",
      "PQ Valve Not Working",
      "Heat Exchanger Clogged",
      "Pressure Gauge Faulty"
    ],
    "Injection Unit": [
      "1st Phase Not Working",
      "2nd Phase Not Working",
      "Plunger Reading Not Come",
      "ACC 1 Not Charge",
      "Plunger Return Problem",
      "Plunger Forward Problem",
      "Intensification Not Working",
      "ACC 2 Not Charge",
      "N2 Leakage/Pressure low",
      "Follow Through Not Working",
      "Metal Pressure Not Come",
      "ACC Charging Not Hold",
      "Servo Filter Alarm",
      "Hyd Valve Not Working",
      "Pressure Transducer Not Working",
      "Hyd Oil Leakage",
      "SDDV Alarm",
      "Injection Booster Not Working",
      "Safety Valve Problem",
      "DC Valve Coil/PCB Faulty",
      "Pressure Gauge Faulty",
      "Servo Valve Alarm",
      "Injection Feedback Alarm",
      "Filter Clogged Alarm",
      "Line Pressure Alarm",
      "Proportional Valve Not Working",
      "Back Pressure Valve Not Working",
      "Injection Pressure Not Holding"
    ],
    "Die Closing Unit": [
      "Die Open Close Reading Not Show",
      "Die Position Origin Problem",
      "Die Open/Close Speed Problem",
      "Die Open/Close Encoder Fault",
      "Shot Light Not Come",
      "DC Valve Coil/PCB Faulty",
      "Die closing Cyl Not Working",
      "Toggle Alingment Problem",
      "Tie Bar Split Nut Close Signal Missing",
      "Tie Bar Liner In Signal Missing",
      "Die Closing Cyl Leak",
      "Hyd. Pressure Problem",
      "Abnormal Locking Force"
    ],
    "Die Height System": [
      "Motor/ Hyd. Motor Not Working",
      "Gear Jam Problem",
      "Shoe Height Not Proper",
      "Die Hight Limit Over",
      "Hyd Oil Leakage",
      "Toggle Alingment Problem",
      "Tie Bar Split Nut Close Signal Missing",
      "Tie Bar Liner In Signal Missing",
      "Die Height Encoder Not Working"
    ],
    "Toggle Mechanism": [
      "Tie Bar Broken",
      "Toggle Pin Broken",
      "Toogle Pin Lock Problem",
      "Toggle Bush Wornout",
      "Abnormal Sound From Toggle",
      "Tie Bar IN Signal Missing",
      "Shoe Wornout",
      "Shoe Plate Bolt Broken",
      "Insufficient/No Lubrication"
    ],
    "Tie Bar & Removal Mechanism": [
      "Tie Bar Front Nut Broken",
      "Tie Bar In Signal Missing",
      "Tie Bar Split Nut Close Signal Missing",
      "Tie Bar Bush Worn Out",
      "Tie Bar Rear Liner In Signal Missing",
      "Tie Bar Rear Liner Out Signal Missing",
      "Tie Bar Removal Cyl Not Working",
      "Tie Bar Removal Cyl Hyd Leakage",
      "Tie Bar Thread Damage",
      "Tie Bar Rear Gear Nut Damage",
      "Tie Bar Wear Seal Damage",
      "Tie Bar Insufficient Lubrication"
    ],
    "Die Clamper": [
      "Die Clamper Oil Leakage",
      "Piston Pump Not Working",
      "Die Clamper Pipe Line Oil Leakage",
      "Die Clamper Limit Switch Signal Problem",
      "Die Clamper Dc Valve Not Working",
      "Die Clamp Tank Oil Level Low",
      "Dc Valve Coil/Pcb Faulty",
      "Pressure Gauge Faulty",
      "Die Clamper Cyl Not Working",
      "Die Clamper Cyl Signal Missing"
    ],
    "Core Unit": [
      "Core In/Out Signal Problem",
      "Core Limit Switch Wire Short",
      "Dc Valve Coil/Pcb Faulty",
      "Core Valve Supply Not Come",
      "Hyd. Pressure Problem",
      "Squeeze Valve Not Working"
    ],
    "Machine Lubrication System": [
      "Machine Lube Level Low",
      "Suction Filter Clogged",
      "Lube Line Leakage",
      "Lubrication Motor Faulty",
      "Lubrication Timer Faulty",
      "Contactor Failure",
      "Lubrication Pressure Problem",
      "Lube Cartridge Problem"
    ],
    "Plunger Lubrication System": [
      "Plunger Lube Level Low",
      "Suction Filter Clogged",
      "Plunger Lube Pressure Problem",
      "Diaphrgam Valve Faulty",
      "Plunger Lube Dc Valve Faulty",
      "Plunger Lube Line Chock",
      "No Air Pressure"
    ],
    "Auto Laddle Unit": [
      "Arm Motor Not Working",
      "Arm Inverter Fault",
      "Arm Motor Brake Problem",
      "Arm Chain Broken",
      "Cup Motor Not Working",
      "Cup Bearing Jam",
      "Cup Inverter Fault",
      "Cup Motor Brake Problem",
      "Cup Chain Broken",
      "Proximity Problem",
      "Sensor Electrode Problem",
      "Sensor Wire Broken",
      "Ladle Position Encoder Fault",
      "Ladle Cup Encoder Fault",
      "Cam Multilimit Switch Fault",
      "Traverse Motion Not Working",
      "Up Down Motion Not Working"
    ],
    "Ejector": [
      "Ejector Encoder Fault",
      "Ejector Pressure Problem",
      "Ejector Dc Valve Not Working",
      "Dc Valve Coil/Pcb Faulty",
      "Ejector Seamless Pipe Oil Leakage",
      "Ejector Piston Rod Seal Oil Leakage",
      "Ejector Cyl Not Working",
      "Ejector Limitswitch Not Working"
    ],
    "Front Safety Door": [
      "Safety Door Invertor Fault",
      "Door Roller Problem",
      "Door Roller Bearing Jam",
      "Door Slide Problem",
      "Safety Door Limit Switch Problem",
      "Safety Door Pneumatic Cylinder Problem",
      "Safety Door Pneumatic Valve Problem",
      "Drive Chain/Belt Broken",
      "Air Leakage",
      "Safety Bar Problem",
      "Motor Not Working",
      "Motor Drive Fault"
    ],
    "Rear Safety Door": [
      "Safety Door Invertor Fault",
      "Door Roller Problem",
      "Door Roller Bearing Jam",
      "Door Slide Problem",
      "Safety Door Limit Switch Problem",
      "Safety Door Pneumatic Cylinder Problem",
      "Safety Door Pneumatic Valve Problem",
      "Drive Chain/Belt Broken",
      "Air Leakage",
      "Safety Bar Problem",
      "Motor Not Working",
      "Motor Drive Fault"
    ],
    "Liner Conveyor": [
      "Liner conveyor forward limit",
      "Power Off (Trip)",
      "Sensor Problem",
      "Over Fluid",
      "Slow Sensor Not working",
      "Stop Conveyor Not Working",
      "Fixed not in Position"
    ],
    "Plunger Beads Unit": [
      "Shot beads hose Blockage",
      "Air Hose Damage",
      "Open close Cylinder Jam",
      "Power Trip"
    ],
    "Liner Heater": [
      "Cooling Alarm",
      "FWD/Backward problem",
      "Voltage Alarm",
      "Air Hose damage",
      "Sensor not Working",
      "Up/Down Problem",
      "Over Temperature",
      "IGBT Failure",
      "Power Trip"
    ],
    "Quenching Tank B/D": [
      "Up/Down problem",
      "Part Sensor Not Working",
      "Air Leak",
      "Up/down cylinder Struck up",
      "Other"
    ],
    "Marking Machine": [
      "Marking Machine Temperature High",
      "Power Trip/Off",
      "Marking not visible"
    ],
    "Cutting Machine": [
      "Overload Alarm",
      "Bearing Problem",
      "Mounting Loosen/Broken",
      "Motor Trip/Power Off"
    ],
    "Vacuum Unit": [
      "Power Trip/off",
      "Reading Error",
      "Cooling Fan not working",
      "Oil level Low",
      "Command Cable Not Working/Damage",
      "Oil leakage",
      "Smoke Issue",
      "Motor Not running"
    ],
    "Die Coat Tank Unit": [
      "Pump Motor Not working",
      "Mixing Motor Not Working",
      "Pressure Not Working",
      "R.O water Not Coming",
      "R.O Water Line Motor Not Working",
      "Mix-up Ratio Problem",
      "Power Trip",
      "Display Not Working"
    ],
    "Jet Cooling Unit": [
      "Diaphragm Failure",
      "Pressure Not Reach(Air/Water)",
      "Water Level Float Not Working",
      "Air Hose Damage",
      "Power Trip/Off",
      "Valve Blockage/Failure",
      "Cycle not on in Auto mode",
      "Pressure Poke Yoke Not Working"
    ],
    "Chiller Unit": [
      "Chiller Water temperature High",
      "Water Pressure Low",
      "Air Lock",
      "Chiller Power Trip/Off",
      "Chiller Temperature Poke Yoke Not Working",
      "Pipe Line Broken"
    ],
    "Heat treatment T5 Furnace": [
      "Loading conveyor FWD not working",
      "Unloading conveyor FWD not working",
      "Zone 1,2,3 Conveyor FWD not working",
      "Temperature not reach",
      "Blower Motor not working",
      "Power trip-off",
      "Front door Not open",
      "Rear door Not open",
      "Hydraulic oil temperature high",
      "Hydraulic oil leak",
      "Hydraulic oil level low",
      "Zone 1,2,3 motor not working",
      "Zone 2 conveyor chain link broken",
      "Part Loading Sensor Not Working",
      "Front & rear door not lock/unlock"
    ],
    "Oil chiller": [
      "Oil chiller Trip-off",
      "Oil temperature high",
      "Chiller fan not working"
    ],
    "Part sensor": [
      "Part Sensor Not Working",
      "Part sensor cable damage",
      "Sensor broken",
      "Sensor mounting bracket broken"
    ],
    "Die Support SMED": [
      "Cylinder FWD/BWD not working",
      "SMED Bed shoe damage",
      "SMED Cylinder oil leak",
      "Lubrication pipe broken",
      "Valve stuck-up"
    ],
    "Oil Leak": [
      "Oil level low",
      "Pump Side oil leak",
      "Injection Side oil leak",
      "Ejection cylinder Oil leak",
      "Die Closing Cylinder Oil leak",
      "Core valve Oil leak"
    ],
    "Heating Cooling": [
      "Temperature Not Reached",
      "Pipe Line water leak",
      "Cooling Unit Not Working",
      "Power trip/off"
    ]
  },
  "Management Loss": {
    "No Reason": ["No Reason"],
    "No BOP": [
      "BOP Not Available"
    ],
    "No Material": [
      "Raw Material Not Available",
      "Molten Metal Not Available",
      "Casting Not Available"
    ],
    "No Manpower": [
      "Opeator Not Planned",
      "Operator Unplanned Absentism"
    ],
    "No Power": [
      "State Power Not Available",
      "DG power not working"
    ],
    "No Air": [
      "Compressor Not Working",
      "Pipe line Burst"
    ],
    "No Water": [
      "Pump Not Working",
      "Water Level Low in Cooling Tower"
    ],
    "No Internet": [
      "No Reason"
    ],
    "EOT Crane": [
      "Crane not working",
      "Crane under service",
      "Crane remote not working"
    ],
    "Plan stop": [
      "Die temperature checking",
      "Plunger water leak checking",
      "Die Cooling line checking",
      "Spray tool Nozzle checking",
      "Vacuum Filter Cleaning",
      "Die Surface Cleaning"
    ]
  },
  "Die Breakdown": {
    "No Reason": ["No Reason"],
    "Vaccum Jam": [
      "No Reason",
      "Fix",
      "Moving"
    ],
    "Soldering": [
      "No Reason",
      "Fix",
      "Moving",
      "Slide",
      "Squeeze Area"
    ],
    "Chip-Off": [
      "No Reason",
      "Fix",
      "Moving",
      "Slide"
    ],
    "Core Pin Broken": [
      "No Reason",
      "Fix",
      "Moving",
      "Slide",
      "Squeeze"
    ],
    "Core Pin Bend": [
      "No Reason",
      "Fix",
      "Moving",
      "Slide",
      "Squeeze"
    ],
    "Slide Core Jam": [
      "No Reason",
      "Fix",
      "Moving",
      "Slide",
      "Squeeze"
    ],
    "Signal Missing": [
      "No Reason"
    ],
    "Cooling Leakage": [
      "No Reason",
      "Fix",
      "Moving",
      "Slide"
    ],
    "Casting Jam": [
      "No Reason",
      "Fix",
      "Moving",
      "Slide"
    ],
    "Adaptor Broken": [
      "No Reason",
      "Fix",
      "Moving",
      "Slide"
    ],
    "CYL Leakage": [
      "No Reason",
      "Fix",
      "Moving",
      "Slide",
      "Squeeze"
    ],
    "Catching": [
      "No Reason",
      "Fix",
      "Moving",
      "Slide"
    ],
    "Limit Switch Plate Bolt Broken": [
      "No Reason",
      "Fix",
      "Moving",
      "Slide",
      "Squeeze"
    ],
    "Limit Switch Rod Bend": [
      "No Reason",
      "Fix",
      "Moving",
      "Slide"
    ],
    "Slide Core Not Out": [
      "No Reason",
      "Top",
      "Bottom",
      "Helper",
      "Operator"
    ],
    "Die Flash Clean": [
      "No Reason",
      "Fix",
      "Moving",
      "Slide"
    ],
    "Chill Vent Broken": [
      "No Reason",
      "Fix",
      "Moving"
    ],
    "Jet Cooling Jam": [
      "No Reason",
      "Fix",
      "Moving",
      "Slide"
    ],
    "Ejector Pin Broken": [
      "No Reason",
      "Fix",
      "Moving"
    ]
  },
  "Robot Breakdown": {
    "No Reason": ["No Reason"],
    "Spray Robot": [
      "No Reason",
      "Axis-1 Reducer Problem",
      "Axis-2 Reducer Problem",
      "Axis-3 Reducer Problem",
      "Axis-4 Reducer Problem",
      "Axis-5 Reducer Problem",
      "Axis-6 Reducer Problem",
      "Axis-1 Servo Problem",
      "Axis-2 Servo Problem",
      "Axis-3 Servo Problem",
      "Axis-4 Servo Problem",
      "Axis-5 Servo Problem",
      "Axis-6 Servo Problem",
      "Axis-1 Encoder Problem",
      "Axis-2 Encoder Problem",
      "Axis-3 Encoder Problem",
      "Axis-4 Encoder Problem",
      "Axis-5 Encoder Problem",
      "Axis-6 Encoder Problem",
      "Communication Issue",
      "Teach Pendent Not Working",
      "Teach Pendent Cable Damage",
      "Power Cable Damage",
      "Robot Wire Harness Damage",
      "Fuse Blown Alarm",
      "Servo Alarm",
      "Control Panel Problem",
      "Emergency Board Not Working",
      "Amplifire Card Not Working",
      "Power Supply Faulty",
      "Cooling Fan Not Working",
      "Transformer Damage",
      "Control Contactor Not Working",
      "Drag Chain Damage",
      "Lm Guide Wornout",
      "Lm Block Damage",
      "7Th Axis Servo Motor Problem",
      "7Th Axis Gear Box Damage",
      "Gear Box Pinion Loose",
      "Rack Damage",
      "Insufficient Lubrication"
    ],
    "Extractor Robot": [
      "No Reason",
      "Axis-1 Reducer Problem",
      "Axis-2 Reducer Problem",
      "Axis-3 Reducer Problem",
      "Axis-4 Reducer Problem",
      "Axis-5 Reducer Problem",
      "Axis-6 Reducer Problem",
      "Axis-1 Servo Problem",
      "Axis-2 Servo Problem",
      "Axis-3 Servo Problem",
      "Axis-4 Servo Problem",
      "Axis-5 Servo Problem",
      "Axis-6 Servo Problem",
      "Axis-1 Encoder Problem",
      "Axis-2 Encoder Problem",
      "Axis-3 Encoder Problem",
      "Axis-4 Encoder Problem",
      "Axis-5 Encoder Problem",
      "Axis-6 Encoder Problem",
      "Communication Issue",
      "Teach Pendent Not Working",
      "Teach Pendent Cable Damage",
      "Power Cable Damage",
      "Robot Wire Harness Damage",
      "Fuse Blown Alarm",
      "Servo Alarm",
      "Control Panel Problem",
      "Emergency Board Not Working",
      "Amplifire Card Not Working",
      "Power Supply Faulty",
      "Cooling Fan Not Working",
      "Transformer Damage",
      "Control Contactor Not Working",
      "Drag Chain Damage",
      "Lm Guide Wornout",
      "Lm Block Damage",
      "7Th Axis Servo Motor Problem",
      "7Th Axis Gear Box Damage",
      "Gear Box Pinion Loose",
      "Rack Damage",
      "Insufficient Lubrication"
    ],
    "Deflashing Robot 1": [
      "No Reason",
      "Axis-1 Reducer Problem",
      "Axis-2 Reducer Problem",
      "Axis-3 Reducer Problem",
      "Axis-4 Reducer Problem",
      "Axis-5 Reducer Problem",
      "Axis-6 Reducer Problem",
      "Axis-1 Servo Problem",
      "Axis-2 Servo Problem",
      "Axis-3 Servo Problem",
      "Axis-4 Servo Problem",
      "Axis-5 Servo Problem",
      "Axis-6 Servo Problem",
      "Axis-1 Encoder Problem",
      "Axis-2 Encoder Problem",
      "Axis-3 Encoder Problem",
      "Axis-4 Encoder Problem",
      "Axis-5 Encoder Problem",
      "Axis-6 Encoder Problem",
      "Communication Issue",
      "Teach Pendent Not Working",
      "Teach Pendent Cable Damage",
      "Power Cable Damage",
      "Robot Wire Harness Damage",
      "Fuse Blown Alarm",
      "Servo Alarm",
      "Control Panel Problem",
      "Emergency Board Not Working",
      "Amplifire Card Not Working",
      "Power Supply Faulty",
      "Cooling Fan Not Working",
      "Transformer Damage",
      "Control Contactor Not Working",
      "Drag Chain Damage",
      "Lm Guide Wornout",
      "Lm Block Damage",
      "7Th Axis Servo Motor Problem",
      "7Th Axis Gear Box Damage",
      "Gear Box Pinion Loose",
      "Rack Damage",
      "Insufficient Lubrication"
    ],
    "Deflashing Robot 2": [
      "No Reason",
      "Axis-1 Reducer Problem",
      "Axis-2 Reducer Problem",
      "Axis-3 Reducer Problem",
      "Axis-4 Reducer Problem",
      "Axis-5 Reducer Problem",
      "Axis-6 Reducer Problem",
      "Axis-1 Servo Problem",
      "Axis-2 Servo Problem",
      "Axis-3 Servo Problem",
      "Axis-4 Servo Problem",
      "Axis-5 Servo Problem",
      "Axis-6 Servo Problem",
      "Axis-1 Encoder Problem",
      "Axis-2 Encoder Problem",
      "Axis-3 Encoder Problem",
      "Axis-4 Encoder Problem",
      "Axis-5 Encoder Problem",
      "Axis-6 Encoder Problem",
      "Communication Issue",
      "Teach Pendent Not Working",
      "Teach Pendent Cable Damage",
      "Power Cable Damage",
      "Robot Wire Harness Damage",
      "Fuse Blown Alarm",
      "Servo Alarm",
      "Control Panel Problem",
      "Emergency Board Not Working",
      "Amplifire Card Not Working",
      "Power Supply Faulty",
      "Cooling Fan Not Working",
      "Transformer Damage",
      "Control Contactor Not Working",
      "Drag Chain Damage",
      "Lm Guide Wornout",
      "Lm Block Damage",
      "7Th Axis Servo Motor Problem",
      "7Th Axis Gear Box Damage",
      "Gear Box Pinion Loose",
      "Rack Damage",
      "Insufficient Lubrication"
    ],
    "Deflashing Robot 3": [
      "No Reason",
      "Axis-1 Reducer Problem",
      "Axis-2 Reducer Problem",
      "Axis-3 Reducer Problem",
      "Axis-4 Reducer Problem",
      "Axis-5 Reducer Problem",
      "Axis-6 Reducer Problem",
      "Axis-1 Servo Problem",
      "Axis-2 Servo Problem",
      "Axis-3 Servo Problem",
      "Axis-4 Servo Problem",
      "Axis-5 Servo Problem",
      "Axis-6 Servo Problem",
      "Axis-1 Encoder Problem",
      "Axis-2 Encoder Problem",
      "Axis-3 Encoder Problem",
      "Axis-4 Encoder Problem",
      "Axis-5 Encoder Problem",
      "Axis-6 Encoder Problem",
      "Communication Issue",
      "Teach Pendent Not Working",
      "Teach Pendent Cable Damage",
      "Power Cable Damage",
      "Robot Wire Harness Damage",
      "Fuse Blown Alarm",
      "Servo Alarm",
      "Control Panel Problem",
      "Emergency Board Not Working",
      "Amplifire Card Not Working",
      "Power Supply Faulty",
      "Cooling Fan Not Working",
      "Transformer Damage",
      "Control Contactor Not Working",
      "Drag Chain Damage",
      "Lm Guide Wornout",
      "Lm Block Damage",
      "7Th Axis Servo Motor Problem",
      "7Th Axis Gear Box Damage",
      "Gear Box Pinion Loose",
      "Rack Damage",
      "Insufficient Lubrication"
    ],
    "Insert Feeding Robot": [
      "No Reason",
      "Axis-1 Reducer Problem",
      "Axis-2 Reducer Problem",
      "Axis-3 Reducer Problem",
      "Axis-4 Reducer Problem",
      "Axis-5 Reducer Problem",
      "Axis-6 Reducer Problem",
      "Axis-1 Servo Problem",
      "Axis-2 Servo Problem",
      "Axis-3 Servo Problem",
      "Axis-4 Servo Problem",
      "Axis-5 Servo Problem",
      "Axis-6 Servo Problem",
      "Axis-1 Encoder Problem",
      "Axis-2 Encoder Problem",
      "Axis-3 Encoder Problem",
      "Axis-4 Encoder Problem",
      "Axis-5 Encoder Problem",
      "Axis-6 Encoder Problem",
      "Communication Issue",
      "Teach Pendent Not Working",
      "Teach Pendent Cable Damage",
      "Power Cable Damage",
      "Robot Wire Harness Damage",
      "Fuse Blown Alarm",
      "Servo Alarm",
      "Control Panel Problem",
      "Emergency Board Not Working",
      "Amplifire Card Not Working",
      "Power Supply Faulty",
      "Cooling Fan Not Working",
      "Transformer Damage",
      "Control Contactor Not Working",
      "Drag Chain Damage",
      "Lm Guide Wornout",
      "Lm Block Damage",
      "7Th Axis Servo Motor Problem",
      "7Th Axis Gear Box Damage",
      "Gear Box Pinion Loose",
      "Rack Damage",
      "Insufficient Lubrication"
    ],
    "Spray Tool & Mixing Unit": [
      "No Reason",
      "Spray Dyecoat Blow Problem",
      "Spary Air Blow Problem",
      "Spray Dyecoat Leakage",
      "Air Leakage",
      "Diaphrgam Valve Faulty",
      "Dc Valve Coil/Pcb Faulty",
      "Dyecoat Filter Clogged",
      "Water Pump Not Working",
      "Stirer Motor Not Working",
      "Dyecoat Level Switch Not Working",
      "Rotary Joint/Coupling Broken",
      "Hose Burst/Puncture",
      "Air Filter Clogged",
      "Wire Short",
      "Home Position Limit Switch Problem",
      "Sensor Input Not Coming",
      "Dosing Pump Not Working",
      "Plc In Fault Mode"
    ],
    "Extractor Gripper": [
      "No Reason",
      "Actuator Not Working/Jam",
      "Clamp Signal Missing",
      "Unclamp Signal Missing",
      "Sol Valve Not Working",
      "Cable Short",
      "Cable Broken/Damage",
      "Cable Dress Pack Worn Out",
      "Part Presence Sensor Not Working",
      "Air Hose Burst",
      "Flow Control Damage",
      "Gripper Finger Damage",
      "Air Pressure Not Sufficient",
      "Locating Pin Damage",
      "Resting Pin/Pad Damage"
    ],
    "Deflashing-1 Gripper": [
      "No Reason",
      "Actuator Not Working/Jam",
      "Clamp Signal Missing",
      "Unclamp Signal Missing",
      "Sol Valve Not Working",
      "Cable Short",
      "Cable Broken/Damage",
      "Cable Dress Pack Worn Out",
      "Part Presence Sensor Not Working",
      "Air Hose Burst",
      "Flow Control Damage",
      "Gripper Finger Damage",
      "Air Pressure Not Sufficient",
      "Locating Pin Damage",
      "Resting Pin/Pad Damage"
    ],
    "Deflashing-2 Gripper": [
      "No Reason",
      "Actuator Not Working/Jam",
      "Clamp Signal Missing",
      "Unclamp Signal Missing",
      "Sol Valve Not Working",
      "Cable Short",
      "Cable Broken/Damage",
      "Cable Dress Pack Worn Out",
      "Part Presence Sensor Not Working",
      "Air Hose Burst",
      "Flow Control Damage",
      "Gripper Finger Damage",
      "Air Pressure Not Sufficient",
      "Locating Pin Damage",
      "Resting Pin/Pad Damage"
    ],
    "Deflashing-3 Gripper": [
      "No Reason",
      "Actuator Not Working/Jam",
      "Clamp Signal Missing",
      "Unclamp Signal Missing",
      "Sol Valve Not Working",
      "Cable Short",
      "Cable Broken/Damage",
      "Cable Dress Pack Worn Out",
      "Part Presence Sensor Not Working",
      "Air Hose Burst",
      "Flow Control Damage",
      "Gripper Finger Damage",
      "Air Pressure Not Sufficient",
      "Locating Pin Damage",
      "Resting Pin/Pad Damage"
    ],
    "Insert Feeding Gripper": [
      "No Reason",
      "Actuator Not Working/Jam",
      "Clamp Signal Missing",
      "Unclamp Signal Missing",
      "Sol Valve Not Working",
      "Cable Short",
      "Cable Broken/Damage",
      "Cable Dress Pack Worn Out",
      "Part Presence Sensor Not Working",
      "Air Hose Burst",
      "Flow Control Damage",
      "Gripper Finger Damage",
      "Air Pressure Not Sufficient",
      "Locating Pin Damage",
      "Resting Pin/Pad Damage"
    ]
  },
  "Planned Downtime": {
    "No Reason": ["No Reason"],
    "PM Plan": [
      "No Reason",
      "Machine Planned Maintenance",
      "Automation Work",
      "Fabrication Work"
    ],
    "JH Activity": [
      "No Reason",
      "Machine Cleaning",
      "Ladle Coating",
      "Die Surface Cleaning",
      "Tag Removal/Kaizen",
      "Others"
    ],
    "Die Trial": [
      "No Reason",
      "New Die Trial",
      "Running Die Trial",
      "Tonnage Change Trial"
    ]
  },
  "Process Loss": {
    "No Reason": ["No Reason"],
    "Plunger": [
      "No Reason",
      "Plunger Jam",
      "Plunger Broken",
      "Plunger Thread Wear Out /Slip",
      "Plunger Life Over",
      "Runner Broken"
    ],
    "Ejector Rod": [
      "No Reason",
      "Ejector Rod Broken",
      "Ejector Rod Thread Wear Out",
      "Ejector Rod Bend",
      "Ejector Nut Loose"
    ],
    "Plunger Adopter": [
      "No Reason",
      "Adopter Broken",
      "Adopter Thread Washout"
    ],
    "Ladle Cup": [
      "No Reason",
      "Ladle Cup Broken",
      "Ladle Cup Leakage",
      "Ladle Cup Change As Per Die",
      "Ladle Cup Mounting Hole Oval"
    ],
    "Holding Furnace Pot": [
      "No Reason",
      "Pot Leakage",
      "Pot Life Over"
    ],
    "Spray": [
      "No Reason",
      "Spray Nozzle Chock",
      "Spray Pipe Leakage",
      "Air Pipe Leakage",
      "Spray Header Change"
    ],
    "Robot": [
      "No Reason",
      "Robot Teaching",
      "Robot Clamping",
      "Robot Finger Broken /Bolt Broken",
      "Robot Air Pipe Leakage",
      "Others"
    ],
    "Setting": [
      "No Reason",
      "Parameter Setting",
      "Spray Setting",
      "Others"
    ],
    "Cooling Leakage": [
      "No Reason",
      "Plunger Rod Cooling Leak",
      "Plunger Cooling Leak",
      "Sleeve Cooling Leakage",
      "Header Hose Burst / Change"
    ],
    "Die Clamp": [
      "No Reason",
      "Clamp Bolt Broken",
      "Die Clamp Bolt Loose"
    ],
    "Injection Unit": [
      "No Reason",
      "Plunger Rod Change",
      "Injection Coupling Change /Packing Provide",
      "Injection Coupling Bolt Broken/Loose",
      "Shot Sleeve Change",
      "Shot Sleeve Housing Change"
    ],
    "Vacuum": [
      "No Reason",
      "Vacuum Filter Clean",
      "Vacuum Pipe Change"
    ],
    "Hydraulic Oil Leakage": [
      "No Reason",
      "Oil Leakage From Qrc",
      "Oil Leakage From Hyd Nipple",
      "Hydraulic Hose Burst"
    ],
    "Jet Cooling": [
      "No Reason",
      "Jet Cooling Header Leakage",
      "Jet Cooling Nrv Jam/Change",
      "Jet Cooling Hose Pipe Change",
      "Jet Cooling Hose Pipe Leakage"
    ],
    "Die Change Over": [
      "No Reason",
      "Unplanned Die Change",
      "Plan Die Change"
    ],
    "Shot sleeve": [
      "No Reason",
      "Sleeve Life completed",
      "Sleeve crack",
      "Sleeve worn-out",
      "Sleeve damage",
      "Sleeve adaptor broken or thread washout",
      "Sleeve position change"
    ],
    "Holding furnace": [
      "No Reason",
      "Dross cleaning",
      "Crucible change",
      "Crucible crack",
      "Thermocouple change",
      "Thermocouple not working",
      "Metal temp low / High"
    ],
    "Plunger lube nozzle": [
      "No Reason",
      "Nozzle blockage",
      "Lube hose damage",
      "Lube oil leak"
    ],
    "Plunger rod": [
      "No Reason",
      "Plunger rod water leak",
      "Plunger rod Bend",
      "Plunger rod cooling not effective",
      "Plunger rod cooler pipe damage",
      "Plunger spacer damage"
    ],
    "Plunger rod coupling": [
      "No Reason",
      "Thread out",
      "Coupling Loose",
      "Coupling damage"
    ],
    "Injection height block": [
      "No Reason",
      "Height adjustment",
      "Height block damage"
    ]
  },
  "HPDC Machine Accessories": {
    "No Reason": ["No Reason"],
    "Holding Furnace": [
      "No Reason",
      "Holding Furnace Temperature Low",
      "Heating Element Broken",
      "Aluminum Braid Damaged",
      "Fuse Blown",
      "Contactor Failure",
      "Thermocouple Faulty",
      "Temperature Controller Problem",
      "Thyrister Panel Problem",
      "Earting Problem",
      "Furnace Cover Close Signal Missing",
      "Crucible Damage",
      "Lining Damage",
      "Thimble Broken",
      "Wire Short",
      "Step Down Transformer Failed"
    ],
    "Vaccum System": [
      "No Reason",
      "Vacuum Motor Overheat",
      "Vacuum Not Start",
      "Vacuum Pressure Not Build Up",
      "Vacuum Oil Leakage",
      "HMI Not Working",
      "Touch Not Working",
      "Plc In Fault Mode",
      "Contactor Failure",
      "Relay Faulty",
      "Selector Switch / Push Button Faulty",
      "Suction Pipe Line Problem",
      "Filter Choke",
      "Oil Filter Choke",
      "Valve Not Working",
      "Dc Valve Coil/Pcb Faulty",
      "Air Leakage",
      "Pressure Gauge Faulty"
    ],
    "Jet Cooling": [
      "No Reason",
      "Jet Cooling Motor Not Working",
      "Water Pump Damage",
      "Hmi Not Working",
      "Touch Not Working",
      "Water Leakage",
      "Drive Tripped",
      "Pneumatic Valve Not Working",
      "Diaphrgam Valve Faulty",
      "Plc In Fault Mode",
      "Contactor Failure",
      "Power Supply Faulty",
      "Relay Faulty",
      "Selector Switch / Push Button Faulty",
      "Pressure Gauge Faulty"
    ],
    "Thermoregulation": [
      "No Reason",
      "Temperature Not Display",
      "Channel-1 Not Working",
      "Channel-2 Not Working",
      "Control Card Failed",
      "Power Card Failed",
      "Thyristor Failed",
      "Contactor Not Working",
      "Main Mcb Tripped",
      "Communication Failure"
    ],
    "Chiller System": [
      "No Reason",
      "Water Pump Pressure Problem",
      "Water Temperature High",
      "Pump Motor Faulty",
      "Contactor Failure",
      "Water Leakage",
      "Water Level Low",
      "Water Over Flow",
      "Cooling Fan Motor Problem",
      "Fins Broken",
      "Gas Leakage",
      "Compressor Problem",
      "Controller Card Problem",
      "Thermocouple Faulty",
      "Temperature Controller Problem",
      "Heat Exchanger Problem"
    ],
    "Cooling Tower": [
      "No Reason",
      "Water Pump Pressure Problem",
      "Pump Motor Faulty",
      "Contactor Failure",
      "Water Leakage",
      "Water Level Low",
      "Water Over Flow",
      "Cooling Fan Motor Problem",
      "Fins Broken"
    ],
    "Water Quenching": [
      "No Reason",
      "Water Temperature High",
      "Level Control Not Working",
      "Pump Not Working",
      "Motor Not Working",
      "Heat Exchnger Not Effective"
    ],
    "Conveyor": [
      "No Reason",
      "Drive Motor Not Working",
      "Gear Box Damage",
      "Limitswitch Not Working",
      "Proximity Not Working",
      "Chain Loose",
      "Slat Damage",
      "Dog Damage",
      "Blower Motor Not Working",
      "Impller Damage",
      "Contactor Not Working"
    ],
    "Liner Heater": [
      "No Reason",
      "Induction Heater Coil Not Working",
      "Thyristor Failed",
      "Fuse Blown",
      "Heat Exchnger Not Effective",
      "Water Level Low",
      "Water Flow Not Sufficient",
      "Temperature Not Rising",
      "Temperature Sensor Not Working",
      "Temperature Display Not Working",
      "Part Presence Sensor Not Working"
    ]
  }
};
